name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: conanio/gcc10:latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake . -DCMAKE_BUILD_TYPE=Release -GNinja
    - name: build
      run: cmake --build .
    - name: test
      run: cmake --build . --target test
