name: C/C++ CI

on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: cblauvelt/cpp-builder-gcc10:latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake . -DCMAKE_BUILD_TYPE=Release -GNinja
    - name: build
      run: cmake --build .
    - name: test
      run: ctest -C Release -T test --output-on-failure --timeout 10
    - name: conan create
      run: conan create .
      